name: hybrid-ad-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - matplotlib
  - numpy
  - pandas
  - pytorch
  - tensorboard
  - scikit-learn
  - plotly
  - pip
  - pip:
    - ipykernel
    - pytorch-lightning
    - nbformat
